### ISSUE TITLE
notice message by cron display 2 times

### ISSUE THREAD

**Issue by ozon** [ozon/b3-plugin-weaponlimiterbf3#4]

**Comment by thomasleveil** [comment]
make sure this is not just the b3 running two times. I've been there ;)

**Comment by ozon** [comment]
b3 was not running 2 times. I see that Problem ingame and note it here. But the problem dosnt come up again.

btw...Checks b3 for a running instance of itself?

**Comment by ozon** [comment]
Ah, just ingame and the msg come 4time up. If i remember right - it is the 4 round. If the Plugin is active - it add the crontab on every map/round start. I should implement a check for existing crontabs
